definitions:
  auth.LoginReq:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  auth.LoginRes:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  auth.RefreshTokenReq:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  auth.RefreshTokenRes:
    properties:
      access_token:
        type: string
    type: object
  auth.RegisterUserReq:
    properties:
      email:
        type: string
      name:
        maxLength: 100
        minLength: 3
        type: string
      password:
        minLength: 6
        type: string
      phone:
        type: string
      role:
        enum:
        - user
        - vendor
        type: string
    required:
    - email
    - name
    - password
    - phone
    - role
    type: object
  user.ResetPasswordReq:
    properties:
      current_password:
        minLength: 6
        type: string
      id:
        type: integer
      new_password:
        minLength: 6
        type: string
    required:
    - current_password
    - new_password
    type: object
  user.UpdateUserReq:
    properties:
      id:
        type: integer
      name:
        maxLength: 100
        minLength: 3
        type: string
      phone:
        type: string
      role:
        enum:
        - user
        - vendor
        type: string
    required:
    - id
    - name
    - phone
    - role
    type: object
  user.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      phone:
        type: string
      role:
        type: string
      updated_at:
        type: string
    type: object
  utils.MessageRes:
    properties:
      message:
        type: string
      success:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login a user, on success get the refreshToken and accessToken
      parameters:
      - description: Login request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: Login response
          schema:
            $ref: '#/definitions/auth.LoginRes'
        "400":
          description: Default response
          schema:
            $ref: '#/definitions/utils.MessageRes'
        "401":
          description: Default response
          schema:
            $ref: '#/definitions/utils.MessageRes'
      summary: Login user
      tags:
      - auth
  /auth/refresh-token:
    post:
      consumes:
      - application/json
      description: Refresh token, send the new access token based on refresh token
      parameters:
      - description: Refresh token request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.RefreshTokenReq'
      produces:
      - application/json
      responses:
        "200":
          description: Refresh token response
          schema:
            $ref: '#/definitions/auth.RefreshTokenRes'
        "400":
          description: Default response
          schema:
            $ref: '#/definitions/utils.MessageRes'
        "401":
          description: Default response
          schema:
            $ref: '#/definitions/utils.MessageRes'
      summary: Refresh token
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user with the provided details
      parameters:
      - description: User registration request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterUserReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.MessageRes'
      summary: Register a new user
      tags:
      - auth
  /users/{user_id}:
    post:
      consumes:
      - application/json
      description: Get User Details by provided ID in url
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.MessageRes'
      summary: Get User Details
      tags:
      - user
  /users/{user_id}/delete:
    delete:
      consumes:
      - application/json
      description: Delete User Details by provided ID in url
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.MessageRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.MessageRes'
      summary: Delete User Details
      tags:
      - user
  /users/{user_id}/password-reset:
    put:
      consumes:
      - application/json
      description: Reset User Password by provided ID in url and password in body
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: Password change request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/user.ResetPasswordReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.MessageRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.MessageRes'
      summary: Reset User Password
      tags:
      - user
  /users/{user_id}/update:
    put:
      consumes:
      - application/json
      description: Update User Details by provided ID in url and details in body
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User Update request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/user.UpdateUserReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.MessageRes'
      summary: Update User Details
      tags:
      - user
swagger: "2.0"
