version: '3'

services:
  postgres:
    image: postgres:16.3-alpine
    ports:
      - 5432:5432
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: e-commerce
    volumes:
      - ./database/data/postgres:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 5000:8080