CREATE TABLE "products" (
  "id" SERIAL PRIMARY KEY,
  "vendor_id" INTEGER NOT NULL,
  "name" VARCHAR(100) NOT NULL,
  "description" VARCHAR(255),
  "price" DECIMAL(10, 2) NOT NULL DEFAULT 0,
  "stock_count" INTEGER NOT NULL DEFAULT 0,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP ,

  CONSTRAINT "fk_vendor_id"
    FOREIGN KEY ("vendor_id")
    REFERENCES "users" ("id")
    ON DELETE CASCADE
);